/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools / Templates
 * and open the template in the editor.
 */
package lab8_jamilgarcia;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ComboBox;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author JamilGarcía
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_NombreSV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sl_poder = new javax.swing.JSlider();
        sp_anios = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_planeta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        b_agregarSV = new javax.swing.JButton();
        rd_Humano = new javax.swing.JRadioButton();
        rd_Amanto = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_NombreUn = new javax.swing.JTextField();
        b_agregarUn = new javax.swing.JButton();
        cb_SerVivo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tf_planetaM = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        rd_humanoM = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        tf_NombreMod = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        sl_PoderM = new javax.swing.JSlider();
        sp_aniosM = new javax.swing.JSpinner();
        rd_amantoM = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        b_SerVIvo = new javax.swing.JButton();
        cb_SeresVivos = new javax.swing.JComboBox<>();
        cb_Universos = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel1.setText("Nombre: ");

        jLabel2.setText("Poder: ");

        sl_poder.setMajorTickSpacing(1);
        sl_poder.setMaximum(10);
        sl_poder.setMinimum(1);
        sl_poder.setPaintLabels(true);
        sl_poder.setPaintTicks(true);
        sl_poder.setSnapToTicks(true);

        sp_anios.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel3.setText("Años:");

        jLabel4.setText("Planeta:");

        jLabel5.setText("Raza:");

        jLabel6.setText("Ser Vivo:");

        b_agregarSV.setText("Agregar Ser Vivo");
        b_agregarSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_agregarSVMouseClicked(evt);
            }
        });

        buttonGroup1.add(rd_Humano);
        rd_Humano.setSelected(true);
        rd_Humano.setText("Humano");

        buttonGroup1.add(rd_Amanto);
        rd_Amanto.setText("Amanto");

        jLabel7.setText("Agregar Ser Vivo");

        jLabel8.setText("Agregar Universo");

        jLabel9.setText("Nombre: ");

        b_agregarUn.setText("Agregar Universo");
        b_agregarUn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_agregarUnMouseClicked(evt);
            }
        });

        jButton1.setText("Cargar Todo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sl_poder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_NombreSV, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rd_Humano)
                                .addGap(18, 18, 18)
                                .addComponent(rd_Amanto))
                            .addComponent(b_agregarSV)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tf_planeta, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sp_anios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)))))
                .addGap(195, 195, 195)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_NombreUn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b_agregarUn)
                            .addComponent(cb_SerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_NombreSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_NombreUn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(sl_poder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sp_anios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_planeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(b_agregarUn)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(cb_SerVivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rd_Humano)
                    .addComponent(rd_Amanto))
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_agregarSV)
                    .addComponent(jButton1))
                .addGap(93, 93, 93))
        );

        jTabbedPane1.addTab("Agregar", jPanel1);

        jLabel10.setText("Planeta:");

        jLabel11.setText("Raza:");

        jButton3.setText("Modificar Ser Vivo");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        buttonGroup2.add(rd_humanoM);
        rd_humanoM.setSelected(true);
        rd_humanoM.setText("Humano");

        jLabel12.setText("Nombre: ");

        jLabel13.setText("Poder: ");

        sl_PoderM.setMajorTickSpacing(1);
        sl_PoderM.setMaximum(10);
        sl_PoderM.setMinimum(1);
        sl_PoderM.setPaintLabels(true);
        sl_PoderM.setPaintTicks(true);
        sl_PoderM.setSnapToTicks(true);

        buttonGroup2.add(rd_amantoM);
        rd_amantoM.setText("Amanto");

        jLabel14.setText("Años:");

        jLabel15.setText("Modificar Ser Vivo");

        b_SerVIvo.setText("Eliminar Ser VIvo");
        b_SerVIvo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_SerVIvoMouseClicked(evt);
            }
        });

        cb_SeresVivos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_SeresVivosItemStateChanged(evt);
            }
        });

        jLabel25.setText("Universo:");

        jLabel26.setText("SerVivo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(20, 20, 20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sl_PoderM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_NombreMod, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tf_planetaM, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sp_aniosM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(70, 70, 70)
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addComponent(cb_SeresVivos, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cb_Universos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(rd_humanoM)
                                    .addGap(18, 18, 18)
                                    .addComponent(rd_amantoM)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jButton3)
                        .addGap(81, 81, 81)
                        .addComponent(b_SerVIvo)))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel13)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel14)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel10)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel11)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(cb_Universos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_NombreMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_SeresVivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addGap(31, 31, 31)
                        .addComponent(sl_PoderM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(sp_aniosM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(tf_planetaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rd_humanoM)
                            .addComponent(rd_amantoM))))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(b_SerVIvo))
                .addGap(81, 81, 81))
        );

        jTabbedPane1.addTab("Modificar/Eliminar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        GuardarTodo();
       
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void cb_SeresVivosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_SeresVivosItemStateChanged
        // TODO add your handling code here:
        int flag = cb_SeresVivos.getSelectedIndex();
        String nombre, planeta, raza;
        int poder, anios;
        SeresVivos SV = null;
        if (flag > -1) {
            SV = SereV.get(flag);
            try {
                tf_NombreMod.setText(SV.getNombre());
                sl_PoderM.setValue(SV.getPoder());
                sp_aniosM.setValue(SV.getAnios());
                tf_planetaM.setText(SV.getPlaneta());
                if (SV.getRaza().equals("Humano")) {
                    rd_humanoM.setSelected(true);
                } else {
                    rd_amantoM.setSelected(true);
                }
                cb_Universos.setSelectedIndex(SV.getUniversoSV());

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error 404!!!");
            }

        }
    }//GEN-LAST:event_cb_SeresVivosItemStateChanged

    private void b_SerVIvoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_SerVIvoMouseClicked
        // TODO add your handling code here:

        try {
            int flag = cb_SeresVivos.getSelectedIndex();
            if (flag == -1) {

            } else {
                SeresVivos SV = SereV.get(flag);
                for (int i = 0; i < Uni.get(SV.getUniversoSV()).getSeres().size(); i++) {
                    if (Uni.get(SV.getUniversoSV()).getSeres().get(i) == SV) {
                        Uni.get(SV.getUniversoSV()).getSeres().remove(i);
                    }
                }
                SereV.remove(flag);
                CargarComboBox(SereV);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error 404!!");
        }
    }//GEN-LAST:event_b_SerVIvoMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:

        String nombre, planeta, raza;
        int poder, anios, flag = cb_SeresVivos.getSelectedIndex();
        try {
            nombre = tf_NombreMod.getText();
            poder = sl_PoderM.getValue();
            anios = (int) sp_aniosM.getValue();
            planeta = tf_planetaM.getText();
            if (rd_humanoM.isSelected() == true) {
                raza = "Humano";
            } else {
                raza = "Amanto";
            }
            SereV.set(flag, new SeresVivos(nombre, poder, anios, planeta, raza, cb_Universos.getSelectedIndex()));
            JOptionPane.showMessageDialog(this, "Accion con exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Algo salio mal, revise los datos");
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void b_agregarUnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_agregarUnMouseClicked
        // TODO add your handling code here:
        try {
            if (cb_SerVivo.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(this, "Elegia un ser vivo");
            } else {
                int flag = cb_SerVivo.getSelectedIndex();
                String nombre = tf_NombreUn.getText();
                SeresVivos SV = SereV.get(flag);
                Uni.add(new Universo(nombre));
                Uni.get(Uni.size() - 1).seres.add(SV);
                //System.out.println(Uni.size());
                Universo Univer = new Universo(nombre);
                Univer.setSer(SV);
                SereV.get(Uni.size() - 1).setUniversoSV(Uni.size() - 1);
                AdminUniverso ap = new AdminUniverso("./ficheros/Universo.tcr");
                ap.cargarArchivo();
                ap.setUniverso(Univer);
                ap.escribirArchivo();
                JOptionPane.showMessageDialog(this, "Accion con exito");
                CargarComboBox(SereV);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Algo salió mal, revise los datos");
        }
    }//GEN-LAST:event_b_agregarUnMouseClicked

    private void b_agregarSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_agregarSVMouseClicked
        // TODO add your handling code here:

        String nombre, planeta, raza;
        int poder, anios;
        try {
            nombre = tf_NombreSV.getText();
            poder = sl_poder.getValue();
            anios = (int) sp_anios.getValue();
            planeta = tf_planeta.getText();
            if (rd_Humano.isSelected() == true) {
                raza = "Humano";
            } else {
                raza = "Amanto";
            }
            SeresVivos SV = new SeresVivos(nombre, poder, anios, planeta, raza, -1);
            SereV.add(new SeresVivos(nombre, poder, anios, planeta, raza, -1));
            JOptionPane.showMessageDialog(this, "Accion con exito");
            AdminSeresVivos ap = new AdminSeresVivos("./ficheros/SeresVivos.tcr");
            ap.cargarArchivo();
            ap.setSeresV(SV);
            ap.escribirArchivo();
            CargarComboBox(SereV);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Algo salio mal, revise los datos");
        }
    }//GEN-LAST:event_b_agregarSVMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        CargarTodo();
    }//GEN-LAST:event_jButton1MouseClicked

    public void CargarComboBox(ArrayList<SeresVivos> SV) {
        DefaultComboBoxModel model
                = (DefaultComboBoxModel) cb_SerVivo.getModel();
        model.removeAllElements();
        for (int i = 0; i < SV.size(); i++) {
            model.addElement(SV.get(i));
        }
        cb_SerVivo.setModel(model);
        cb_SeresVivos.setModel(model);

        DefaultComboBoxModel model2
                = (DefaultComboBoxModel) cb_Universos.getModel();
        model2.removeAllElements();
        for (int i = 0; i < Uni.size(); i++) {
            model2.addElement(Uni.get(i));
        }
        cb_Universos.setModel(model2);
    }

    public void CargarTodo() {
        AdminSeresVivos as = new AdminSeresVivos("./ficheros/SeresVivos.tcr");
        AdminUniverso au = new AdminUniverso("./ficheros/Universo.tcr");
        as.cargarArchivo();
        au.cargarArchivo();
        SereV = as.getListaSV();
        Uni = au.getListaUni();
        CargarComboBox(SereV);
    }

    public void GuardarTodo() {
        AdminSeresVivos as = new AdminSeresVivos("./ficheros/SeresVivos.tcr");
        AdminUniverso au = new AdminUniverso("./ficheros/Universo.tcr");
        as.cargarArchivo();
        for (int i = 0; i < SereV.size()/2; i++) {
            as.setSeresV(SereV.get(i));
        }
        as.escribirArchivo();
        au.cargarArchivo();
        for (int i = 0; i < Uni.size()/2; i++) {
            au.setUniverso(Uni.get(i));
        }
        au.escribirArchivo();
        CargarComboBox(SereV);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_SerVIvo;
    private javax.swing.JButton b_agregarSV;
    private javax.swing.JButton b_agregarUn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cb_SerVivo;
    private javax.swing.JComboBox<String> cb_SeresVivos;
    private javax.swing.JComboBox<String> cb_Universos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rd_Amanto;
    private javax.swing.JRadioButton rd_Humano;
    private javax.swing.JRadioButton rd_amantoM;
    private javax.swing.JRadioButton rd_humanoM;
    private javax.swing.JSlider sl_PoderM;
    private javax.swing.JSlider sl_poder;
    private javax.swing.JSpinner sp_anios;
    private javax.swing.JSpinner sp_aniosM;
    private javax.swing.JTextField tf_NombreMod;
    private javax.swing.JTextField tf_NombreSV;
    private javax.swing.JTextField tf_NombreUn;
    private javax.swing.JTextField tf_planeta;
    private javax.swing.JTextField tf_planetaM;
    // End of variables declaration//GEN-END:variables

    ArrayList<SeresVivos> SereV = new ArrayList();
    ArrayList<Universo> Uni = new ArrayList();

}
